[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
docs = { path = "../docs" }
askama = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
